package com.compomics.denovogui.gui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Simple dialog to set the PepNovo location.
 *
 * @author Harald Barsnes
 */
public class LocationDialog extends javax.swing.JDialog {

    /**
     * Reference to the DeNovoGUI main frame.
     */
    private DeNovoGUI deNovoGUI;

    /**
     * Creates a new PepNovoLocationDialog.
     *
     * @param deNovoGUI the DeNovoGUI main frame
     * @param modal
     */
    public LocationDialog(DeNovoGUI deNovoGUI, boolean modal) {
        super(deNovoGUI, modal);
        initComponents();
        this.deNovoGUI = deNovoGUI;

        if (deNovoGUI.getPepNovoFolder() != null) {
            pepNovoLocationTextField.setText(new File(deNovoGUI.getPepNovoFolder(), deNovoGUI.getPepNovoExecutable()).getAbsolutePath());
            okButton.setEnabled(deNovoGUI.checkPepNovoFolder(deNovoGUI.getPepNovoFolder()));
        }
        if (deNovoGUI.getDirecTagFolder()!= null) {
            direcTagLocationTextField.setText(new File(deNovoGUI.getDirecTagFolder(), deNovoGUI.getDirecTagExecutable()).getAbsolutePath());
            okButton.setEnabled(deNovoGUI.checkDirecTagFolder(deNovoGUI.getDirecTagFolder()));
        }

        setLocationRelativeTo(deNovoGUI);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        pepNovoLocationPanel = new javax.swing.JPanel();
        pepNovoLocationLabel = new javax.swing.JLabel();
        pepNovoLocationTextField = new javax.swing.JTextField();
        popNovoLocationBrowseButton = new javax.swing.JButton();
        direcTagLocationLabel = new javax.swing.JLabel();
        direcTagLocationTextField = new javax.swing.JTextField();
        direcTagLocationBrowseButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PepNovo Location");

        backgroundPanel.setBackground(new java.awt.Color(230, 230, 230));

        pepNovoLocationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Executables"));
        pepNovoLocationPanel.setOpaque(false);

        pepNovoLocationLabel.setText("PepNovo+ Location");

        popNovoLocationBrowseButton.setText("Browse");
        popNovoLocationBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popNovoLocationBrowseButtonActionPerformed(evt);
            }
        });

        direcTagLocationLabel.setText("DirecTag Location");

        direcTagLocationBrowseButton.setText("Browse");
        direcTagLocationBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direcTagLocationBrowseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pepNovoLocationPanelLayout = new javax.swing.GroupLayout(pepNovoLocationPanel);
        pepNovoLocationPanel.setLayout(pepNovoLocationPanelLayout);
        pepNovoLocationPanelLayout.setHorizontalGroup(
            pepNovoLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pepNovoLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pepNovoLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pepNovoLocationPanelLayout.createSequentialGroup()
                        .addComponent(pepNovoLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pepNovoLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(popNovoLocationBrowseButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pepNovoLocationPanelLayout.createSequentialGroup()
                        .addComponent(direcTagLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(direcTagLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(direcTagLocationBrowseButton)))
                .addContainerGap())
        );
        pepNovoLocationPanelLayout.setVerticalGroup(
            pepNovoLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pepNovoLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pepNovoLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pepNovoLocationLabel)
                    .addComponent(pepNovoLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(popNovoLocationBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pepNovoLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direcTagLocationLabel)
                    .addComponent(direcTagLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direcTagLocationBrowseButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("OK");
        okButton.setEnabled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pepNovoLocationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );

        backgroundPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pepNovoLocationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Set the PepNovo location.
     *
     * @param evt
     */
    private void popNovoLocationBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popNovoLocationBrowseButtonActionPerformed
        browsePepNovoExecutable();
    }//GEN-LAST:event_popNovoLocationBrowseButtonActionPerformed

    /**
     * Set the PepNovo location and close the dialog.
     *
     * @param evt
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Close the dialog without saving.
     *
     * @param evt
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Set the DirecTag location.
     *
     * @param evt
     */
    private void direcTagLocationBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direcTagLocationBrowseButtonActionPerformed
        browseDirecTagExecutable();
    }//GEN-LAST:event_direcTagLocationBrowseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton direcTagLocationBrowseButton;
    private javax.swing.JLabel direcTagLocationLabel;
    private javax.swing.JTextField direcTagLocationTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel pepNovoLocationLabel;
    private javax.swing.JPanel pepNovoLocationPanel;
    private javax.swing.JTextField pepNovoLocationTextField;
    private javax.swing.JButton popNovoLocationBrowseButton;
    // End of variables declaration//GEN-END:variables

    /**
     * This method is called when the Browse button for PepNovo is pressed.
     */
    public void browsePepNovoExecutable() {

        String startLocation = pepNovoLocationTextField.getText();
        JFileChooser fc = new JFileChooser(startLocation);
        int result = fc.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File pepNovoExecutable = fc.getSelectedFile();

            if (deNovoGUI.checkPepNovoFolder(pepNovoExecutable.getParentFile())) {
                deNovoGUI.setLastSelectedFolder(pepNovoExecutable.getAbsolutePath());
                deNovoGUI.setPepNovoFolder(pepNovoExecutable.getParentFile());
                deNovoGUI.setPepNovoExecutable(pepNovoExecutable.getName());
                pepNovoLocationTextField.setText(pepNovoExecutable.getAbsolutePath());
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect PepNovo executable selected.\n"
                        + "Please try again, or press cancel to exit.",
                        "Incorrect PepNovo Executable", JOptionPane.WARNING_MESSAGE);
                browsePepNovoExecutable();
            }
        }

        okButton.setEnabled(deNovoGUI.checkPepNovoFolder(deNovoGUI.getPepNovoFolder()));
    }
    
    /**
     * This method is called when the Browse button for DirecTag is pressed.
     */
    public void browseDirecTagExecutable() {

        String startLocation = direcTagLocationTextField.getText();
        JFileChooser fc = new JFileChooser(startLocation);
        int result = fc.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File direcTagExecutable = fc.getSelectedFile();

            if (deNovoGUI.checkDirecTagFolder(direcTagExecutable.getParentFile())) {
                deNovoGUI.setLastSelectedFolder(direcTagExecutable.getAbsolutePath());
                deNovoGUI.setDirecTagFolder(direcTagExecutable.getParentFile());
                deNovoGUI.setDirecTagExecutable(direcTagExecutable.getName());
                direcTagLocationTextField.setText(direcTagExecutable.getAbsolutePath());
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect DirecTag executable selected.\n"
                        + "Please try again, or press cancel to exit.",
                        "Incorrect DirecTag Executable", JOptionPane.WARNING_MESSAGE);
                browseDirecTagExecutable();
            }
        }

        okButton.setEnabled(deNovoGUI.checkDirecTagFolder(deNovoGUI.getDirecTagFolder()));
    }
}
