package com.compomics.denovogui.gui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Simple dialog to set the PepNovo location.
 *
 * @author Harald Barsnes
 */
public class PepNovoLocationDialog extends javax.swing.JDialog {

    /**
     * Reference to the DeNovoGUI main frame.
     */
    private DeNovoGUI deNovoGUI;

    /**
     * Creates a new PepNovoLocationDialog.
     *
     * @param deNovoGUI the DeNovoGUI main frame
     * @param modal
     */
    public PepNovoLocationDialog(DeNovoGUI deNovoGUI, boolean modal) {
        super(deNovoGUI, modal);
        initComponents();
        this.deNovoGUI = deNovoGUI;

        if (deNovoGUI.getPepNovoFolder() != null) {
            pepNovoLocationTextField.setText(deNovoGUI.getPepNovoFolder().getAbsolutePath());
            okButton.setEnabled(deNovoGUI.checkPepNovoFolder(deNovoGUI.getPepNovoFolder()));
        }

        setLocationRelativeTo(deNovoGUI);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        pepNovoLocationPanel = new javax.swing.JPanel();
        pepNovoLocationLabel = new javax.swing.JLabel();
        pepNovoLocationTextField = new javax.swing.JTextField();
        popNovoLocationBrowseButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PepNovo Location");

        backgroundPanel.setBackground(new java.awt.Color(230, 230, 230));

        pepNovoLocationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Executable Folder"));
        pepNovoLocationPanel.setOpaque(false);

        pepNovoLocationLabel.setText("PepNovo Location");

        popNovoLocationBrowseButton.setText("Browse");
        popNovoLocationBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popNovoLocationBrowseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pepNovoLocationPanelLayout = new javax.swing.GroupLayout(pepNovoLocationPanel);
        pepNovoLocationPanel.setLayout(pepNovoLocationPanelLayout);
        pepNovoLocationPanelLayout.setHorizontalGroup(
            pepNovoLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pepNovoLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pepNovoLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pepNovoLocationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(popNovoLocationBrowseButton)
                .addContainerGap())
        );
        pepNovoLocationPanelLayout.setVerticalGroup(
            pepNovoLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pepNovoLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pepNovoLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pepNovoLocationLabel)
                    .addComponent(pepNovoLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(popNovoLocationBrowseButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("OK");
        okButton.setEnabled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pepNovoLocationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );

        backgroundPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pepNovoLocationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Set the PepNovo location.
     *
     * @param evt
     */
    private void popNovoLocationBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popNovoLocationBrowseButtonActionPerformed
        browsePepnovoFolder();
    }//GEN-LAST:event_popNovoLocationBrowseButtonActionPerformed

    /**
     * Set the PepNovo location and close the dialog.
     *
     * @param evt
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        deNovoGUI.setPepNovoFolder(new File(pepNovoLocationTextField.getText()));
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Close the dialog without saving.
     *
     * @param evt
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel pepNovoLocationLabel;
    private javax.swing.JPanel pepNovoLocationPanel;
    private javax.swing.JTextField pepNovoLocationTextField;
    private javax.swing.JButton popNovoLocationBrowseButton;
    // End of variables declaration//GEN-END:variables

    /**
     * This method is called when the Browse button for PepNovo is pressed.
     */
    public void browsePepnovoFolder() {

        String startLocation = pepNovoLocationTextField.getText();
        JFileChooser fc = new JFileChooser(startLocation);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fc.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File pepNovoFolder = fc.getSelectedFile();

            if (deNovoGUI.checkPepNovoFolder(pepNovoFolder)) {
                deNovoGUI.setLastSelectedFolder(pepNovoFolder.getAbsolutePath());
                deNovoGUI.setPepNovoFolder(pepNovoFolder);
                pepNovoLocationTextField.setText(pepNovoFolder.getAbsolutePath());
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect PepNovo folder specified.\n"
                        + "Please try again, or press cancel to exit.",
                        "Incorrect PepNovo Folder", JOptionPane.WARNING_MESSAGE);
                browsePepnovoFolder();
            }
        }

        okButton.setEnabled(deNovoGUI.checkPepNovoFolder(deNovoGUI.getPepNovoFolder()));
    }
}
