/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.denovogui.gui;

/**
 *
 * @author tmuth
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        inputFilesPnl = new javax.swing.JPanel();
        inputFilesLbl = new javax.swing.JLabel();
        inputFilesTtf = new javax.swing.JTextField();
        inputFilesBrowseBtn = new javax.swing.JButton();
        inputClearBtn = new javax.swing.JButton();
        exeFolderPnl = new javax.swing.JPanel();
        exeFolderLbl = new javax.swing.JLabel();
        exeFolderTtf = new javax.swing.JTextField();
        exeFolderBrowseBtn = new javax.swing.JButton();
        outputFolderPnl = new javax.swing.JPanel();
        outputFolderLbl = new javax.swing.JLabel();
        outputFolderTtf = new javax.swing.JTextField();
        outputFolderBrowseBtn = new javax.swing.JButton();
        logPnl = new javax.swing.JPanel();
        settingsPnl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        modelCbx = new javax.swing.JComboBox();
        modelLbl = new javax.swing.JLabel();
        enzymeCbx = new javax.swing.JComboBox();
        fragIonTolLbl = new javax.swing.JLabel();
        fragIonTolSpn = new javax.swing.JSpinner();
        precTolLbl = new javax.swing.JLabel();
        precTolSpn = new javax.swing.JSpinner();
        solutionsLbl = new javax.swing.JLabel();
        solutionsSpn = new javax.swing.JSpinner();
        chargeCorrChx = new javax.swing.JCheckBox();
        PrecursorCorrChx = new javax.swing.JCheckBox();
        filterQualityChx = new javax.swing.JCheckBox();
        modsPnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modsTbl = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        spectrumViewerPnl = new javax.swing.JPanel();
        querySpectraPnl = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        peptidesPnl = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        histogramPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputFilesPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Files"));

        inputFilesLbl.setText("Spectrum File(s):");

        inputFilesTtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFilesTtfActionPerformed(evt);
            }
        });

        inputFilesBrowseBtn.setText("Browse");
        inputFilesBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFilesBrowseBtnActionPerformed(evt);
            }
        });

        inputClearBtn.setText("Clear");
        inputClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputFilesPnlLayout = new javax.swing.GroupLayout(inputFilesPnl);
        inputFilesPnl.setLayout(inputFilesPnlLayout);
        inputFilesPnlLayout.setHorizontalGroup(
            inputFilesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFilesPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputFilesLbl)
                .addGap(18, 18, 18)
                .addComponent(inputFilesTtf, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(inputFilesBrowseBtn)
                .addGap(11, 11, 11)
                .addComponent(inputClearBtn)
                .addContainerGap())
        );
        inputFilesPnlLayout.setVerticalGroup(
            inputFilesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFilesPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputFilesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputFilesLbl)
                    .addComponent(inputFilesTtf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFilesBrowseBtn)
                    .addComponent(inputClearBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exeFolderPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Executable Folder"));

        exeFolderLbl.setText("PepNovo Location:");

        exeFolderTtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exeFolderTtfActionPerformed(evt);
            }
        });

        exeFolderBrowseBtn.setText("Browse");
        exeFolderBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exeFolderBrowseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exeFolderPnlLayout = new javax.swing.GroupLayout(exeFolderPnl);
        exeFolderPnl.setLayout(exeFolderPnlLayout);
        exeFolderPnlLayout.setHorizontalGroup(
            exeFolderPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exeFolderPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exeFolderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exeFolderTtf)
                .addGap(18, 18, 18)
                .addComponent(exeFolderBrowseBtn)
                .addContainerGap())
        );
        exeFolderPnlLayout.setVerticalGroup(
            exeFolderPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exeFolderPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exeFolderPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exeFolderLbl)
                    .addComponent(exeFolderTtf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exeFolderBrowseBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        outputFolderPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Output Folder"));

        outputFolderLbl.setText("Output Location:");

        outputFolderTtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFolderTtfActionPerformed(evt);
            }
        });

        outputFolderBrowseBtn.setText("Browse");
        outputFolderBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFolderBrowseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout outputFolderPnlLayout = new javax.swing.GroupLayout(outputFolderPnl);
        outputFolderPnl.setLayout(outputFolderPnlLayout);
        outputFolderPnlLayout.setHorizontalGroup(
            outputFolderPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputFolderPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outputFolderLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputFolderTtf)
                .addGap(18, 18, 18)
                .addComponent(outputFolderBrowseBtn)
                .addContainerGap())
        );
        outputFolderPnlLayout.setVerticalGroup(
            outputFolderPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputFolderPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outputFolderPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFolderLbl)
                    .addComponent(outputFolderTtf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputFolderBrowseBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Logging"));

        javax.swing.GroupLayout logPnlLayout = new javax.swing.GroupLayout(logPnl);
        logPnl.setLayout(logPnlLayout);
        logPnlLayout.setHorizontalGroup(
            logPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        logPnlLayout.setVerticalGroup(
            logPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        settingsPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Settings"));

        jLabel4.setText("Enzyme:");

        modelCbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CID_IT_TRYP" }));
        modelCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelCbxActionPerformed(evt);
            }
        });

        modelLbl.setText("Model:");

        enzymeCbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TRYPSIN", "NON_SPECIFIC" }));
        enzymeCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enzymeCbxActionPerformed(evt);
            }
        });

        fragIonTolLbl.setText("Fragment Mass Tolerance:");

        fragIonTolSpn.setModel(new javax.swing.SpinnerNumberModel(0.5d, 0.0d, 2.0d, 0.1d));

        precTolLbl.setText("Precursor Mass Tolerance:");

        precTolSpn.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.0d, 2.0d, 0.01d));

        solutionsLbl.setText("No. Solutions (max. 20):");

        solutionsSpn.setModel(new javax.swing.SpinnerNumberModel(10, 1, 20, 1));

        chargeCorrChx.setText("Use Spectrum Charge (No Correction)");
        chargeCorrChx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeCorrChxActionPerformed(evt);
            }
        });

        PrecursorCorrChx.setText("Use Spectrum Precursor m/z (No Correction)");
        PrecursorCorrChx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecursorCorrChxActionPerformed(evt);
            }
        });

        filterQualityChx.setText("Filter Low Quality Spectra");
        filterQualityChx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterQualityChxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsPnlLayout = new javax.swing.GroupLayout(settingsPnl);
        settingsPnl.setLayout(settingsPnlLayout);
        settingsPnlLayout.setHorizontalGroup(
            settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsPnlLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(enzymeCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(settingsPnlLayout.createSequentialGroup()
                        .addComponent(modelLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modelCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(settingsPnlLayout.createSequentialGroup()
                        .addGroup(settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filterQualityChx)
                            .addComponent(PrecursorCorrChx)
                            .addComponent(chargeCorrChx))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPnlLayout.createSequentialGroup()
                        .addGroup(settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fragIonTolLbl)
                            .addComponent(precTolLbl)
                            .addComponent(solutionsLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(precTolSpn)
                            .addComponent(fragIonTolSpn)
                            .addComponent(solutionsSpn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))))
                .addContainerGap())
        );
        settingsPnlLayout.setVerticalGroup(
            settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPnlLayout.createSequentialGroup()
                .addGroup(settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(enzymeCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fragIonTolLbl)
                    .addComponent(fragIonTolSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precTolLbl)
                    .addComponent(precTolSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(solutionsLbl)
                    .addComponent(solutionsSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chargeCorrChx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PrecursorCorrChx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterQualityChx)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        modsPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifications"));

        modsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fixed", "Variable", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(modsTbl);
        modsTbl.getColumnModel().getColumn(0).setMinWidth(50);
        modsTbl.getColumnModel().getColumn(0).setPreferredWidth(50);
        modsTbl.getColumnModel().getColumn(0).setMaxWidth(50);
        modsTbl.getColumnModel().getColumn(1).setMinWidth(50);
        modsTbl.getColumnModel().getColumn(1).setPreferredWidth(50);
        modsTbl.getColumnModel().getColumn(1).setMaxWidth(50);

        jButton7.setText("Configure");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modsPnlLayout = new javax.swing.GroupLayout(modsPnl);
        modsPnl.setLayout(modsPnlLayout);
        modsPnlLayout.setHorizontalGroup(
            modsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modsPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modsPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton7)))
                .addContainerGap())
        );
        modsPnlLayout.setVerticalGroup(
            modsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modsPnlLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("De Novo Search Run"));

        jLabel9.setText("Progress:");

        jButton4.setText("Start");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton6))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outputFolderPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputFilesPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exeFolderPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modsPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settingsPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputFilesPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exeFolderPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(outputFolderPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(settingsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(modsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("De Novo Search", jPanel1);

        spectrumViewerPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Spectrum Viewer"));

        javax.swing.GroupLayout spectrumViewerPnlLayout = new javax.swing.GroupLayout(spectrumViewerPnl);
        spectrumViewerPnl.setLayout(spectrumViewerPnlLayout);
        spectrumViewerPnlLayout.setHorizontalGroup(
            spectrumViewerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        spectrumViewerPnlLayout.setVerticalGroup(
            spectrumViewerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        querySpectraPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Query Spectra"));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "Spectrum Title", "m/z", "Charge"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout querySpectraPnlLayout = new javax.swing.GroupLayout(querySpectraPnl);
        querySpectraPnl.setLayout(querySpectraPnlLayout);
        querySpectraPnlLayout.setHorizontalGroup(
            querySpectraPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(querySpectraPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );
        querySpectraPnlLayout.setVerticalGroup(
            querySpectraPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(querySpectraPnlLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        peptidesPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("De Novo Peptides"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Peptide", "RankScore", "Score", "N-Gap", "C-Gap", "m/z", "Charge"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout peptidesPnlLayout = new javax.swing.GroupLayout(peptidesPnl);
        peptidesPnl.setLayout(peptidesPnlLayout);
        peptidesPnlLayout.setHorizontalGroup(
            peptidesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peptidesPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );
        peptidesPnlLayout.setVerticalGroup(
            peptidesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peptidesPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(querySpectraPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(peptidesPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spectrumViewerPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spectrumViewerPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peptidesPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(querySpectraPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("De Novo Results", jPanel2);

        histogramPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("De Novo Score Histogram"));

        javax.swing.GroupLayout histogramPnlLayout = new javax.swing.GroupLayout(histogramPnl);
        histogramPnl.setLayout(histogramPnlLayout);
        histogramPnlLayout.setHorizontalGroup(
            histogramPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        histogramPnlLayout.setVerticalGroup(
            histogramPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(histogramPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(histogramPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Statistics", jPanel13);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(199, 199, 199))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFilesTtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFilesTtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFilesTtfActionPerformed

    private void inputFilesBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFilesBrowseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFilesBrowseBtnActionPerformed

    private void inputClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputClearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputClearBtnActionPerformed

    private void exeFolderTtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exeFolderTtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exeFolderTtfActionPerformed

    private void exeFolderBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exeFolderBrowseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exeFolderBrowseBtnActionPerformed

    private void outputFolderTtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFolderTtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputFolderTtfActionPerformed

    private void outputFolderBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFolderBrowseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputFolderBrowseBtnActionPerformed

    private void modelCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelCbxActionPerformed

    private void enzymeCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enzymeCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enzymeCbxActionPerformed

    private void chargeCorrChxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeCorrChxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chargeCorrChxActionPerformed

    private void PrecursorCorrChxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecursorCorrChxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecursorCorrChxActionPerformed

    private void filterQualityChxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterQualityChxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterQualityChxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox PrecursorCorrChx;
    private javax.swing.JCheckBox chargeCorrChx;
    private javax.swing.JComboBox enzymeCbx;
    private javax.swing.JButton exeFolderBrowseBtn;
    private javax.swing.JLabel exeFolderLbl;
    private javax.swing.JPanel exeFolderPnl;
    private javax.swing.JTextField exeFolderTtf;
    private javax.swing.JCheckBox filterQualityChx;
    private javax.swing.JLabel fragIonTolLbl;
    private javax.swing.JSpinner fragIonTolSpn;
    private javax.swing.JPanel histogramPnl;
    private javax.swing.JButton inputClearBtn;
    private javax.swing.JButton inputFilesBrowseBtn;
    private javax.swing.JLabel inputFilesLbl;
    private javax.swing.JPanel inputFilesPnl;
    private javax.swing.JTextField inputFilesTtf;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel logPnl;
    private javax.swing.JComboBox modelCbx;
    private javax.swing.JLabel modelLbl;
    private javax.swing.JPanel modsPnl;
    private javax.swing.JTable modsTbl;
    private javax.swing.JButton outputFolderBrowseBtn;
    private javax.swing.JLabel outputFolderLbl;
    private javax.swing.JPanel outputFolderPnl;
    private javax.swing.JTextField outputFolderTtf;
    private javax.swing.JPanel peptidesPnl;
    private javax.swing.JLabel precTolLbl;
    private javax.swing.JSpinner precTolSpn;
    private javax.swing.JPanel querySpectraPnl;
    private javax.swing.JPanel settingsPnl;
    private javax.swing.JLabel solutionsLbl;
    private javax.swing.JSpinner solutionsSpn;
    private javax.swing.JPanel spectrumViewerPnl;
    // End of variables declaration//GEN-END:variables
}
